---

- name: Ensure base Sonarr directory exists
  ansible.builtin.file:
    path: "{{ sonarr_docker_base_directory }}"
    state: 'directory'
    owner: "{{ sonarr_docker_user }}"
    group: "{{ sonarr_docker_user }}"
    mode: '0755'

- name: Ensure Sonarr compose file is present
  ansible.builtin.template:
    src: 'compose.yml.j2'
    dest: "{{ sonarr_docker_base_directory }}/compose.yml"
    owner: "{{ sonarr_docker_user }}"
    group: "{{ sonarr_docker_user }}"
    mode: '0644'
    backup: true
  register: sonarr_docker_compose_template_result

# - name: Ensure Sonarr compose project is deployed
#   community.docker.docker_compose_v2:
#     project_src: "{{ sonarr_docker_base_directory }}"
#     state: 'present'
#     pull: "{{ sonarr_docker_pull_policy }}"
#     recreate: "{{ 'always' if sonarr_docker_compose_template_result.changed else 'auto' }}"
#     remove_orphans: true

- name: Ensure Sonarr compose project is deployed
  community.docker.docker_compose_v2:
    project_src: "{{ sonarr_docker_base_directory }}"
    state: 'present'
    pull: "{{ 'always' if sonarr_docker_update_image else sonarr_docker_pull_policy }}"
    recreate: "{{ 'always' if (sonarr_docker_compose_template_result.changed or sonarr_docker_update_image) else 'auto' }}"
    remove_orphans: true
